### PR TITLE
Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by reedy**
Fixes https://github.com/php-parallel-lint/PHP-Console-Highlighter/issues/1

### CODE REVIEW

**Comment by reedy** [comment]
Also needs https://github.com/php-parallel-lint/PHP-Console-Highlighter/pull/6

**Comment by grogy** [comment]
Thank you :-) 

Can you add, please, other changes? Diff can you see on https://github.com/php-parallel-lint/PHP-Console-Highlighter/compare/v0.4...HEAD (Travis CI fixes, fixed build script, creating .gitattributes)

**Comment by reedy** [comment]
> Thank you :-)
> 
> Can you add, please, other changes? Diff can you see on [v0.4...HEAD](https://github.com/php-parallel-lint/PHP-Console-Highlighter/compare/v0.4...HEAD) (Travis CI fixes, fixed build script, creating .gitattributes)

It was right when I created it ;)

I can't help feel it would've taken about as long to merge this PR (or edit it) than it would have taken to write the comment asking me to do it though :P

**Comment by grogy** [comment]
Thank you :+1:

**Pull request merged**
