### PR TITLE
CI: switch to ghactions

### LINKED ISSUE #13: Move away from Ant
The build checks being run via `ant` are failing on a number of biulds/PHP versions, but the builds are not being marked as failed. That kind of makes the CI check useless.

See for an example: https://travis-ci.org/github/php-parallel-lint/PHP-Console-Highlighter/jobs/691819847

I'd like to propose to either improve the `ant` setup so the builds fail when they should or to move away from `ant` and instead use a Travis build script calling the intended checks directly.

### LINKED ISSUE #22: Switch to using GH Actions
As Travis for open source has died a quiet dead, I propose switching the CI building over to GH Actions.

I have made preparations to action this. and PR #20 and #21 are preliminary PRs before pulling the PR to switch the CI over.

### PR DESCRIPTION
**Pull request by jrfnl**
### Composer/Ant: move the build scripts to the Composer configuration

As this is a PHP project and the build steps are relatively simple, it will make it more intuitive for contributors to use Composer scripts to run CI checks, than to have to install Ant for this.

This commit creates the same build/CI scripts as were previously available via Ant in the Composer configuration file.

Notes:
- The scripts are set up to respect the PHP version used by Composer (instead of a system default).
- The scripts are set up to work equally well on Linux/Windows/Mac.
- The only two differences are:
    - The `mkdir` and file deletions won't automatically be done anymore.
        Generally speaking, the `mkdir` should only need to be run once anyway and the file deletes should not be necessary as the log files will just be overwritten by the tools, so I deemed this an acceptable trade-off.
    - The `colors` argument won't be set anymore.
        For most tools, this means, the tool will default to automatically determining whether the CLI used supports colourized output.
        As the determination of this in most tools has become pretty good, I, again, deemed this an acceptable trade-off.

### CI: switch to GitHub Actions

This commit:
* Adds a GH Actions `cs` workflow for the code style and vardump checks which were previously run on Travis.
    These checks only need to run against one PHP version as the results will be the same independently of the PHP version these checks are run on.
* Adds a GH Actions `test` workflow for the linting and unit test checks which were previously run on Travis.
* Uses the [`cs2pr`](https://github.com/staabm/annotate-pull-request-from-checkstyle) tool to display the results of the PHP linting and the results of the PHP code style check in-line in the file diff in the PR.
* Removes the, now redundant, `.travis.yml` configuration.
* Updates the `.gitattributes` file.
* Updates the "Build Status" badge in the Readme to use the results from the GH Actions runs.

Fixes #13 
Fixes #22

### CODE REVIEW

**Comment by jrfnl** [comment]
@grogy Could you give the Okay for the GH actions to run on this PR ? That way you can see them in action.

GH made a change recently for security reasons that PRs running actions need to be approved the first time the action is run for a new contributor: https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Comment by grogy** [comment]
In GUI i don't see [approve button](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). 

The PR looks ok - the idea is good and mistakes in implementations we can resolve in next commit. For it - I merge it ;) Thank you

**Comment by grogy** [comment]
You code as a queen! [Works](https://github.com/php-parallel-lint/PHP-Console-Highlighter/runs/2535278998?check_suite_focus=true) great for the first time :rocket:

**Comment by jrfnl** [comment]
@grogy Glad to hear it, though the actions did run in my own fork, so I'd already tested them and made sure everything was okay.

Either way, two down, one more to go - did you see my PR in the Console Color repo ? Once that one is merged, I can pull a similar PR to this there too.

**Pull request merged**
